goal_error: 1e-2
ik_solver: "QPVanilla"
qp_solver: "quadprog"
tikhonov_damp: 1e-3
vel_track_cost: -1.0
posture_cost: -1.0
manipulability_cost: -1.0
ebd_cost: -1.0
respect_joint_limits: False
is_task_2D: False
alpha: 0.01
beta: 1.0
Kp: 1.0
Kv: 0.001
z_only: False
max_init_clik_iterations: 10000
max_running_clik_iterations: 1000
viz_test_path: False
