FROM ubuntu:jammy

LABEL org.opencontainers.image.authors="marko.guberina@control.lth.se"

# install python3-tk without questions
ARG DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Stockholm

RUN apt-get update && apt-get install -y --no-install-recommends \
        python3  \
        python3-pip \
        python3-tk \
        #ipython3 \
        git \
        sudo \
#        man-db \
#        manpages-posix \
        iputils-ping \
        arp-scan \
        # nice to have
#        python3-opencv \
        vim \
        vim-addon-manager \
        vim-youcompleteme \
        vim-python-jedi \
        zsh \
        zsh-syntax-highlighting \
        libarchive-tools \
        libxcb-cursor0\
        libgomp1 \
        python3-python-qt-binding 
        
# qt-binding is a really unnecessary 300MB, but i don't want
# to do more matplotlib hacks
# if you want manuals:
#RUN sed -i 's:^path-exclude=/usr/share/man:#path-exclude=/usr/share/man:' \
#        /etc/dpkg/dpkg.cfg.d/excludes
# we're running out of space on the docker.control
# and noone is reading manuals anyway
#RUN yes | unminimize 

# make the environment more usable
# create user
RUN useradd -m -s /bin/zsh -G sudo -u 1000 student

WORKDIR /home/student/
RUN passwd -d student
USER student
# copy repo to workdir
RUN mkdir SimpleManipulatorControl
COPY --chown=student .. ./SimpleManipulatorControl
RUN mkdir -p .cache/zsh/
COPY --chown=student /dot_files_for_docker/.vimrc /home/student/
COPY --chown=student /dot_files_for_docker/.zshrc /home/student/
COPY --chown=student /dot_files_for_docker/global_extra_conf.py /home/student/


WORKDIR /home/student/
USER student
RUN pip install -e ./SimpleManipulatorControl/python/
RUN pip install pinocchio crocoddyl matplotlib meshcat ur_rtde argcomplete \
                qpsolvers ecos example_robot_data meshcat_shapes \
                pyqt6 opencv-python

RUN vam install python-jedi && vam install youcompleteme
