robot: "ur5e"
robot_mode: "whole_body"
real: False
robot_ip: "127.0.0.1"
ctrl_freq: 500
visualizer: True
viz_update_rate: -1
plotter: True
gripper: "none"
max_iterations: 100000
start_from_current_pose: False
acceleration: 0.3
max_v_percentage: 0.3
debug_prints: False
save_log: False
save_dir: "./data"
run_name: "latest_run"
index_runs: False
past_window_size: 5
controller_speed_scaling: 1.0
contact_detecting_force: 2.8
minimum_detectable_force_norm: 3.0
visualize_collision_approximation: False
