# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message_specs.proto
# Protobuf Python Version: 5.29.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 5, 29, 1, "", "message_specs.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x13message_specs.proto"\x1c\n\x0fjoint_positions\x12\t\n\x01q\x18\x01 \x03(\x01"\x16\n\x05v_cmd\x12\r\n\x05v_cmd\x18\x01 \x03(\x01"3\n\x08wrenches\x12\x0e\n\x06wrench\x18\x01 \x03(\x01\x12\x17\n\x0fwrench_estimate\x18\x02 \x03(\x01"\x18\n\x06wrench\x12\x0e\n\x06wrench\x18\x01 \x03(\x01">\n\x06T_goal\x12\x10\n\x08position\x18\x01 \x03(\x01\x12\x10\n\x08rotation\x18\x02 \x03(\x01\x12\x10\n\x08velocity\x18\x03 \x03(\x01\x62\x08\x65\x64itionsp\xe8\x07'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "message_specs_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_JOINT_POSITIONS"]._serialized_start = 23
    _globals["_JOINT_POSITIONS"]._serialized_end = 51
    _globals["_V_CMD"]._serialized_start = 53
    _globals["_V_CMD"]._serialized_end = 75
    _globals["_WRENCHES"]._serialized_start = 77
    _globals["_WRENCHES"]._serialized_end = 128
    _globals["_WRENCH"]._serialized_start = 130
    _globals["_WRENCH"]._serialized_end = 154
    _globals["_T_GOAL"]._serialized_start = 156
    _globals["_T_GOAL"]._serialized_end = 218
# @@protoc_insertion_point(module_scope)
