from dataclasses import dataclass, field
from smc.bookkeeping.registry import ConfigRegistry


@ConfigRegistry.register("ocp")
@dataclass
class ConfigOptimalControl:
    dt: float = field(
        default=1e-2,
        metadata={"help": "time length between state-control-pair decision variables"},
    )
    n_knots: int = field(
        default=100,
        metadata={"help": "number of state-control-pair decision variables"},
    )
    stop_at_final: bool = field(
        default=False,
        metadata={
            "help": "NOTE: NOT IMPLEMENTED ATM the trajectory generated by the OCP will be followed. it might not have finally velocity 0. if this argument is set to true, the final velocity will be set to 0 (there will be overshoot)."
        },
    )
    solver: str = field(
        default="boxfddp",
        metadata={
            "help": "optimal control problem solver you want",
            "choices": ["boxfddp", "csqp"],
        },
    )
    max_solver_iter: int = field(
        default=200,
        metadata={
            "help": "number of iterations the ocp solver takes. ~100-500 for just ocp (it can converge before ofc), ~10 for mpc"
        },
    )
    ee_pose_cost: float = field(
        default=1e2, metadata={"help": "ee pose cost in pulling mpc"}
    )
    base_translation_cost: float = field(
        default=1e2, metadata={"help": "base translation cost in pulling mpc"}
    )
    x_reg_cost: float = field(default=1e-3, metadata={"help": "state regulation cost"})
    u_reg_cost: float = field(
        default=1e-3, metadata={"help": "control input regulation cost"}
    )
    linearly_increasing_task_cost_factor: float = field(
        default=1.0,
        metadata={
            "help": "the first knot gets task cost you set with --task-cost, after which it's linearly increased until the last knot has this argument * --task-cost"
        },
    )
